#!/bin/bash

# Description: CLI to create a network of web applications (Node.js, Webpack and Sass) with domain names attached to them, can be used directly in the terminal
#	       or called via a server-side application

# Installation: Ensure the file is executable,
# run sudo ./WhiteLabelCLI install (add copy to duplicate the file instead of moving it)

if [ $# -eq 0 ];
	then

	# No argument was supplied so echo out the option parameters
	echo "No arguments supplied"
	echo "Usage:	WhiteLabelCLI [command] [parameter]"
	echo "Options:"
	echo "	instal:	installs the package and makes it available from the CLI through 'WhiteLabelCLI'"
	echo "	build:	builds the application, accepts parameters - [sass | js | deploy]"
	echo "	create:	creates an instance of WhiteLabelCLI and generates a virtual host for it"

else
	if [ "$1" == "install" ];
		then

		# the user is installing WhiteLabelCLI, move/copy the current
		# file to /usr/local/bin and make it accessible from the command line

		Directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

		if [ "$2" == "copy" ];
			then

			cp $Directory/WhiteLabelCLI /usr/local/bin

		else
			mv $Directory/WhiteLabelCLI /usr/local/bin

		fi

		chmod u+x /usr/local/bin/WhiteLabelCLI

		echo "Install complete"
		echo "You can now call WhiteLabelCLI via the command line with: WhiteLabelCLI [command]"

	elif [ "$1" == "start" ];
		then

		# Start an application instance (use in the relevant app directory)	

		echo "Starting WhiteLabelCLI..."

		npm run start

	elif [ "$1" == "build" ];
		then

		# Build an application instance (use in the relevant app directory)	

		if [ "$2" == "sass" ];
			then

			echo "Building App SASS..."

			npm run-script sass

		elif [ "$2" == "js" ];
			then

			echo "Building App JS..."

			npm run-script build

		elif [ "$2" == "deploy" ];
			then

			echo "Deploying App JS..."

			npm run-script deploy

		else
			echo "Building WhiteLabelCLI & App..."

			npm run-script build
			npm run-script sass

		fi

	elif [ "$1" == "create" ];
		then

		# Create an instance of our web app with a domain name attached

		echo "Creating WhiteLabelCLI instance..."

		if [ -z ${2+x} ];		
			then
			
			# Create a virtual host in apache using the domain name supplied
			cp /etc/apache2/sites-available/WhiteLabelCLI_template.conf /etc/apache2/sites-available/$2.conf 
			sed -i -e "s/aliassir/$2/g" /etc/apache2/sites-available/$2.conf
			a2ensite $2.conf
			service apache2 restart

			# Copy and build an instance of our white label web application
			cp -r /home/user/WhiteLabelCLI-appsource /home/user/sites/$2
			chown -R user:user /home/user/sites/$2
			cd /home/user/sites/$2
			npm run build
			npm run start

			echo "WhiteLabelCLI installed, please visit https://www.YOUR_URL/admin/configuration to complete your setup"

		else
			echo "No domain name set"

		fi


	else
		echo "Invalid command"

	fi

fi
